### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by tigermian** [leo-liu/gosogouproxy#1]
./webinterface.go:88: undefined: Asset

**Comment by leo-liu** [comment]
目前的版本需要 `go-bindata` 的支持来嵌入 web 界面和 pac 脚本，自动生成的代码没有放在 git 库里面。
用
```
go get github.com/jteeuwen/go-bindata/go-bindata
```
安装 `go-bindata` 工具，确保它在 `PATH` 路径中，然后可以使用 `src` 目录的 `build` 脚本编译。

**Comment by tigermian** [comment]
哦哦，多谢
